### ISSUE TITLE
Unusual behavior when AlwaysOnTop = screen-saver

### ISSUE THREAD

**Issue by kenjsan** [AryToNeX/Glasstron#136]
As soon as the window loses focus the background turns from glassy too very dark.  Still can see some blur but looks like bg-black opacity-90

Everything looks as it should when widow is in focus.

Main.js
`const mainWindow = createWindow("main", {
    width: 400,
    height: 100,
    resizable: false,
    x: 788,
    y: 1000,
    transparent: true,
    frame: false,
  });`
```
  mainWindow.setAlwaysOnTop(true, "screen-saver");
  mainWindow.setVisibleOnAllWorkspaces(true);
  mainWindow.setFullScreenable(false);
```

**Expected behavior**
Should maintain opacity and blur at constant value regardless of the window that is in focus.

**Desktop **
 - OS: Catalina 10.15.6
 - Glasscord version: 0.0.7

**Comment by AryToNeX** [comment]
Please check the type of vibrancy you set as it could cause such an issue.
Also check if this behaviour is reproducible using Electron alone.

**Comment by kenjsan** [comment]
`visualEffectState: "active"`
fixes the issue

changing vibrancy had no effect other than what color the window would switch to when out of focus

**Comment by AryToNeX** [comment]
okay so I am closing this, glad you fixed that yourself.
