### ISSUE TITLE
Gnome Blur don't work

### ISSUE THREAD

**Issue by SquitchYT** [AryToNeX/Glasstron#146]
**Describe the bug**
In Gnome Shell, the blur background effect don't work. The background is only transparent

**Note:** This issue section is for Glasstron only!
DO NOT report other apps' issues.
More specifically, DO NOT REPORT ANYTHING RELATED SPECIFICALLY TO GLASSCORD HERE!

**To Reproduce**
1. Run your demo on gnome 

**Expected behavior**
A blur effect

**Desktop (please complete the following information):**
 - OS: Fedora 34

**Comment by AryToNeX** [comment]
Hey there! GNOME blur support does not come OOB; rather it depends on a third party extension called 'blur-provider'. If you happen to not have this extension then the effect will not work.

Also it will not work if you are on a Wayland session.

**Comment by SquitchYT** [comment]
Hello. Okay, I don't know that. Thanks for the reply. Bye
