### ISSUE TITLE
Can't Remove White Tint on Windows 11 with Acrylic Blur

### ISSUE THREAD

**Issue by KorbsStudio** [AryToNeX/Glasstron#150]
**Describe the bug**
Looks like __Acrylic__ effect isn't working in Windows 11 Build 22000.5, of course this is an early build of Windows 11.

When using `acrylic` in `blurType`, Electron opens with white background even though I have it set to transparent.

**Expected behavior**
Acrylic effects shows up on Electron like it would with a regular UWP app (e.g. Settings, Calculator).

**Screenshots**
![image](https://user-images.githubusercontent.com/51213244/124062671-1b217f00-d9ff-11eb-8b3a-ba266c76813b.png)
<p style="align: center">Acrylic (Left) | Blurbehind (Right)</p>

**Desktop (please complete the following information):**
 - OS: Windows 11 Build 22000.5
 - Glasscord version: 0.0.7

I believe we should hold off for a bit until more of Windows 11 is completed, after all this is an early build of Windows 11.

**Comment by AryToNeX** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by faresthu** [comment]
Nice:)

**Comment by KorbsStudio** [comment]
Okay it sorta works, but there is a white background I can't get rid of:

https://user-images.githubusercontent.com/51213244/124368576-666ea400-dc30-11eb-975c-a7f264aa4472.mp4

**Comment by AryToNeX** [comment]
Removing the label because the blur is definitely there; as for the tint... man I do not know how to fix it.. probably the tint API still works?? idk

**Comment by KorbsStudio** [comment]
I was only testing Windows 11 for a few days to make sure stuff like this still works in my software.
I'm done testing and no longer have Windows 11, I'm back on Linux.

**Comment by KorbsStudio** [comment]
Tested again, issues remains.
I still don't have Windows 11, tested on someone's system.
