### ISSUE TITLE
Cannot find module './platforms/win32.js'

### ISSUE THREAD

**Issue by Dreaming-Codes** [AryToNeX/Glasstron#152]
**Describe the bug**
I'm using this template but glasstron fail and it didn't find the win32 module.

**To Reproduce**
1. Go to https://github.com/cawa-93/vite-electron-builder
2. Clone this rep
3. Enable glasstron

**Expected behavior**
The app start with no problems

**Screenshots**
![image](https://user-images.githubusercontent.com/10401566/124374442-753e7080-dc9b-11eb-9ca7-986644f760b0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Glasscord version: 0.0.7

**Comment by AryToNeX** [comment]
Quote from the README:
> **NOTICE for projects using Webpack and similar:** Glasstron uses `__dirname` internally, so you have to define it as an external module, or else it won't work on Windows.

Vite is a bundler, just like Webpack or Rollup are. If Glasstron is bundled, there is no way it will work on Windows.
