### ISSUE TITLE
New App Using Glasstron

### ISSUE THREAD

**Issue by Henrylin666** [AryToNeX/Glasstron#19]
I made a new app with Glasstron: Clear Writer
repo link: https://github.com/Henrylin666/ClearWriter
would you like to put this repo onto README.md? :)
(README.md of Clear Writer is written in Chinese, but it also supports English)

**Comment by AryToNeX** [comment]
I checked a bit through your code and I don't feel like it uses glasstron correctly. I cannot put apps who don't use it correctly in the README; besides, version 0.0.4 is out, you might want to update your sources.
