### ISSUE TITLE
So, how do you actually install/use Glasstron? (for those - like myself - who are unfamiliar with how it works)

### ISSUE THREAD

**Issue by DNEAVES** [AryToNeX/Glasstron#3]
I'm pretty unsure of how to actually set up Glasstron. I did the "npm install glasstron" process, but that pretty much the only instruction that actually points to what to do. Am I supposed to move something somewhere? Run something? Edit a snippet of code like Glasscord says to do?

There's also the Glasscord project, which provides a little more of a "what to do", but that hasn't worked for me, with Discord or CodeOSS (which both are shown to work with Glasscord).

**Comment by AryToNeX** [comment]
Glasstron is not intended for end users. It's a library for developers to use in their own applications.
