### ISSUE TITLE
setVibrancy() broken on macOS

### ISSUE THREAD

**Issue by Eugeny** [AryToNeX/Glasstron#55]
```
const { BrowserWindow: GBW } = require('glasstron')
const { app, BrowserWindow: EBW } = require('electron')

app.on('ready', () => {
    let w1 = new GBW({})
    let w2 = new EBW({})
    w1.setVibrancy('fullscreen-ui')
    w2.setVibrancy('fullscreen-ui')
})
```

**Comment by AryToNeX** [comment]
ok but is this on master branch?

**Comment by Eugeny** [comment]
Yep - master. Looks like an array gets passed to `setVibrancy` here: https://github.com/AryToNeX/Glasstron/commit/424075d31a6c240cfce47fc429a6547d8fdf22ee#diff-748ec3715bf7cb233256e7732e80a644d9e75e74a5080942e33ff3cd7e5afe8cR81 and also `_vibrancy[1]` is always `null` if you only use `setVibrancy` without `setBlur`

**Comment by AryToNeX** [comment]
> Yep - master. Looks like an array gets passed to `setVibrancy` here: [424075d#diff-748ec3715bf7cb233256e7732e80a644d9e75e74a5080942e33ff3cd7e5afe8cR81](https://github.com/AryToNeX/Glasstron/commit/424075d31a6c240cfce47fc429a6547d8fdf22ee#diff-748ec3715bf7cb233256e7732e80a644d9e75e74a5080942e33ff3cd7e5afe8cR81) and also `_vibrancy[1]` is always `null` if you only use `setVibrancy` without `setBlur`

I was trying to wrap Electron's `setVibrancy` so that I can also provide a global switch with `setBlur` and a `getVibrancy` method. Not really needed as you know but I want them there. I still lack a Mac to test my approach and maybe there's a bug I never dug up just by looking at the code.

**Comment by AryToNeX** [comment]
Does it work as intended in 0.0.6?

**Comment by Eugeny** [comment]
No. In platforms/darwin.js, `_vibrancy[1]` is used to actually set vibrancy, but it's always null. You probably should check `vibrancy[0]` here: https://github.com/AryToNeX/Glasstron/blob/master/src/platforms/darwin.js#L75

**Comment by AryToNeX** [comment]
Can you test it and make a pull request? I am with you on that one thing, but I got really no time to make the change myself lately.
