### ISSUE TITLE
Which build tools do I need? (Windows)

### ISSUE THREAD

**Issue by daydreamercodes** [AryToNeX/Glasstron#57]
Which build tools do I need to install and use Glasstron on Windows?

**Comment by AryToNeX** [comment]
You would need to install just node-gyp as described in [their README file](https://github.com/nodejs/node-gyp#option-1).

**Comment by daydreamercodes** [comment]
I already have but I'm using VS2017 and Python 2.7 for better-sqlite3. Should I use VS2019 and latest release of Python or send the error?

**Comment by AryToNeX** [comment]
Please update to Glasstron 0.0.6 (released seconds ago) to see if your problems persist.

**Comment by daydreamercodes** [comment]
Solved, thank you!
