### ISSUE TITLE
Abnormal Window Dragging Latency with Acrylic Blur

### ISSUE THREAD

**Issue by meisme-dev** [AryToNeX/Glasstron#59]
**Describe the bug**
Window Dragging Latency

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Acrylic blur in main.js
2. Drag the Window, you will probably notice the latency

**Expected behaviour**
The Window moves normally

**Screenshots**
https://user-images.githubusercontent.com/49573906/104110085-3dcda900-52a2-11eb-88e8-51feecf703f9.mp4

**Desktop (please complete the following information):**
 - OS: Windows Version 10.0.19042 Build 19042

**Comment by AryToNeX** [comment]
This has been known and it is not a bug within Glasstron. Acrylic blur is messing with the mouse polling ratio on the Windows side of composition (aka Microsoft should fix their acrylic implementation for Win32 apps).

If your target for your app is mainly Windows, then there's another project which is Windows-specific and has some workarounds for this specific bug: https://github.com/Seo-Rii/electron-acrylic-window

If your target is multiple platforms (and, especially, Linux), then you might want to use `blurbehind` as a blur type, or just work around those issues yourself, as it doesn't fall into Glasstron's scope to do so.
