### ISSUE TITLE
Window not spawning, error with electron.app.getPath (not found)

### ISSUE THREAD

**Issue by busybox11** [AryToNeX/Glasstron#88]
**Describe the bug**
The window isn't spawning and node is returning an error saying that `electron.app.getPath` is undefined.

**To Reproduce**
1. Try to spawn a window with Glasstron

**Expected behavior**
The window should be created

**Screenshots**
![image](https://user-images.githubusercontent.com/29630035/109038945-8f07ef80-76cc-11eb-9a4c-e6298479b97a.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Glasstron version: `glasstron@0.0.7`
 - Electron version: `electron@11.3.0`
 - nodejs / npm version: `Node.js v15.8.0`, `npm 6.14.11`

**Comment by AryToNeX** [comment]
can I please look at your code send it over discord or something this should not happen

**Comment by AryToNeX** [comment]
wait a minute why are you using node to test that, electron should be launched with `npx electron .` and not `node .`

**Comment by busybox11** [comment]
Oh, that might be why?
I basically copy pasted your test app and injected my html instead. Gotta test it later.

**Comment by nodgear** [comment]
You should launch it by either a binary, or with global package.

resouces folder
or
electron ./project_directory
